env:
  - DOCKER_COMPOSE_VERSION=3

addons:
  apt:
    packages:
      - docker-ce

group: edge
language: php
php:
  - '7.3'

services:
  - docker

before_install:
  - docker-compose build
  - sudo service mysqld stop
  - docker-compose down
  - docker-compose up -d
  - docker exec -it poly_backend mysql -e 'CREATE DATABASE IF NOT EXISTS poly_backend_test;'
  - cp .env.travis .env.testing
  - docker exec -it poly_backend composer self-update
  - docker exec -it poly_backend composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - docker exec -it poly_backend vendor/bin/phpcs --standard=psr2 src/
  - docker exec -it poly_backend vendor/bin/phpunit -- --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
