group: edge
language: php
php:
  - '7.2'
  - '7.3'

services:
  - mysql
  - docker

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS poly_backend_test;'

before_install:
  - docker build -t dominx99/poly-backend .
  - cp .env.travis .env.testing
  - docker exec -it poly_backend composer self-update
  - docker exec -it poly_backend composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - docker exec -it poly_backend vendor/bin/phpcs --standard=psr2 src/
  - docker exec -it poly_backend vendor/bin/phpunit -- --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
