env:
  - DOCKER_COMPOSE_VERSION=3

addons:
  apt:
    packages:
      - docker-ce

group: edge
language: php
php:
  - '7.3'

services:
  - docker

before_install:
  - cp .env.travis .env.testing
  - sudo docker-compose build
  - sudo docker-compose down
  - sudo docker-compose up -d
  - sudo docker exec -t poly_backend mysql -u root -psecret -h db -e 'CREATE DATABASE IF NOT EXISTS poly_backend_test;'
  - sudo docker exec -t poly_backend composer self-update
  - mkdir .composer
  - chmod -R 777 .composer
  - ls -al
  - sudo docker exec -t poly_backend composer self-update
  - sudo docker exec -t poly_backend composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - docker exec -it poly_backend vendor/bin/phpcs --standard=psr2 src/
  - docker exec -it poly_backend vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
