version: "3.3"
services:

  poly_backend:
    image: nginx:alpine
    working_dir: /application
    ports:
      - "80:80"
    volumes:
      - .:/application:delegated
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  db:
    healthcheck:
      test: "cat /proc/net/tcp /proc/net/tcp6 | grep ':0CEA'"
      interval: 10s
      timeout: 5s
      retries: 5
    image: mysql
    volumes:
      - poly_backend_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=poly
      - MYSQL_HOST=127.0.0.1
    ports:
      - "8083:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      cache_from:
        - chylo/poly-backend:latest
    image: chylo/poly-backend:latest
    container_name: poly_backend
    working_dir: /application
    volumes:
      - .:/application:delegated
      - ./docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    links:
      - db

volumes:
  poly_backend_db:
